"""tabelas de carteira, transacao e usuario

Revision ID: 2e155a84346a
Revises: 8b6e33207eab
Create Date: 2026-07-25 09:00:27.211796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e155a84346a'
down_revision: Union[str, None] = '8b6e33207eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('hash_password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('portfolio',
    sa.Column('id_portfolio', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_portfolio')
    )
    op.create_index(op.f('ix_portfolio_id_portfolio'), 'portfolio', ['id_portfolio'], unique=False)
    op.create_table('transaction',
    sa.Column('id_transaction', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('id_portfolio', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='transaction_type_enum', create_constraint=True), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_portfolio'], ['portfolio.id_portfolio'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    op.create_index(op.f('ix_transaction_id_transaction'), 'transaction', ['id_transaction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_id_transaction'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_portfolio_id_portfolio'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
