"""padroniza_precision_rate_fixed_income

Revision ID: 72768f7801ec
Revises: 3a7c9d1e2b4f
Create Date: 2026-08-11 22:26:50.076480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72768f7801ec'
down_revision: Union[str, None] = '3a7c9d1e2b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fixed_income",
        "rate",
        existing_type=sa.Numeric(),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fixed_income",
        "rate",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.Numeric(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
