"""tabelas iniciais de ativos

Revision ID: 8b6e33207eab
Revises: 
Create Date: 2026-07-20 12:14:29.383352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6e33207eab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('type_column', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_table('fixed_income',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cdb',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fgc_covered', sa.Boolean(), nullable=False),
    sa.Column('liquidity_type', sa.Enum('DIARIA', 'NO_VENCIMENTO', 'PERIODICA', name='liquidity_type_enum', create_constraint=True), nullable=False),
    sa.Column('index_type', sa.Enum('CDI', 'IPCA', 'PREFIXADO', name='index_type_enum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['fixed_income.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('government_bond',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('liquidity_type', sa.Enum('DIARIA', 'NO_VENCIMENTO', 'PERIODICA', name='liquidity_type_enum', create_constraint=True), nullable=False),
    sa.Column('bond_index_type', sa.Enum('SELIC', 'IPCA', 'PREFIXADO', name='bond_index_type_enum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['fixed_income.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('government_bond')
    op.drop_table('cdb')
    op.drop_table('fixed_income')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
