"""correção de bugs de portfolio e transaction

Revision ID: e3fdcf5bccc8
Revises: 2e155a84346a
Create Date: 2026-07-26 15:02:55.609417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fdcf5bccc8'
down_revision: Union[str, None] = '2e155a84346a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'wallet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('wallet_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
